EMS/Controllers/AmountController.cs
using AutoMapper;
using Data.FormModels;
using EMS.Constants;
using EMS.Data;
using EMS.Data.Entities.Emp;
using EMS.Data.FormModels.EmpSalary;
using EMS.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Ems1.Controllers
{
    public class AmountController : Controller
    {
        private readonly IAmountService _amountService;
        private readonly IMapper _mapper;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<Employee> _userManager;
        private EmpDbContext _applicationDbContext;

        public AmountController(IAmountService amountService, IEmailSender emailSender, IMapper mapper, UserManager<Employee> userManager, EmpDbContext applicationDbContext)
        {
            _amountService = amountService;
            _emailSender = emailSender;
            _mapper = mapper;
            _userManager = userManager;
            _applicationDbContext = applicationDbContext;
        }

        [Authorize(Roles = "Superadmin")]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var users = await _userManager.GetUsersInRoleAsync(UserRoles.Employee);
            var list = users.Select(x => new SelectListItem { Text = x.UserName, Value = x.Id }).ToList();
            ViewBag.Employee = list;
            return View();
        }

        // POST: Amount/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EmpSalaryVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                string employeeId = _userManager.GetUserId(User);
                var users = await _userManager.GetUsersInRoleAsync(UserRoles.Employee);
                SelectList list = new SelectList(users);
                ViewBag.Employee = list;

                if (model is not null && !string.IsNullOrEmpty(model.RequestingEmpId))
                {
                    if (_amountService.IsSalaryForEmployeeExist(model.RequestingEmpId, DateTime.Now.Month))
                    {
                        ModelState.AddModelError("", "Employee Salary already Credited...");
                        return View(model);
                    }
                    else
                    {
                        var emp = await _userManager.FindByIdAsync(model.RequestingEmpId);
                        EmpSalaryVM amountreqmodel = new EmpSalaryVM
                        {
                            RequestingEmpId = model.RequestingEmpId,
                            SalaryAmount = model.SalaryAmount,
                            Designation = model.Designation,
                            Department = model.Department,
                            GrossSalary = model.GrossSalary,
                            TotalWorkingDays = model.TotalWorkingDays,
                            PaidDays = model.PaidDays,
                            LOPDays = model.LOPDays,
                            BankName = model.BankName,
                            AccountNumber = model.AccountNumber,
                            HRA = model.HRA,
                            NetSalary = model.NetSalary,
                            ConveyanceAllowance = model.ConveyanceAllowance,
                            MedicalAllowance = model.MedicalAllowance,
                            EPF = model.EPF,
                            ProfessionalTax = model.ProfessionalTax,
                            Salarydate = DateTime.Now,
                            CreatedbyId = employeeId
                        };

                        EmpSalary amountRequest = _mapper.Map<EmpSalary>(amountreqmodel);
                        amountRequest.CreatedBy = _userManager.GetUserName(User);
                        await _amountService.AddEmployeeSalary(amountRequest);

                        // Send Email to supervisor and requesting user
                        await _emailSender.SendEmailAsync("admin@localhost.com", "New Leave Request",
                            $"Please review this leave request. <a href='UrlOfApp/{amountRequest.Id}'>Click Here</a>");

                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Something went wrong...");
                    return View(model);
                }
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Something went wrong", ex.Message);
                return View(model);
            }
        }

        [Authorize(Roles = "Employee")]
        [HttpGet]
        public async Task<ActionResult> EmpIndex()
        {
            string employeeid = _userManager.GetUserId(User);      
            var employeeRequests = await _amountService.GetSalaryForEmployee(employeeid);
            foreach (var empSalary in employeeRequests)
            {
                var users = await _userManager.GetUsersInRoleAsync(UserRoles.Employee);
                empSalary.RequestingEmployee = users.Where(x => x.Id == empSalary.RequestingEmpId).FirstOrDefault();
            }

            List<EmpSalaryVM> employeeRequestsModel = _mapper.Map<List<EmpSalaryVM>>(employeeRequests);
            EmployeeDataVm model = new EmployeeDataVm
            {
                AmountVMs = employeeRequestsModel,
            };

            return View(model);
        }

        [Authorize(Roles = "Superadmin")]
        public async Task<ActionResult> Index()
        {
            List<EmpSalary> empSalaries = _amountService.FindAll();
            foreach (var empSalary in empSalaries)
            {
                if(empSalary.RequestingEmployee is null && !string.IsNullOrEmpty(empSalary.RequestingEmpId))
                {
                    var users = await _userManager.GetUsersInRoleAsync(UserRoles.Employee);
                    empSalary.RequestingEmployee = users.Where(x => x.Id == empSalary.RequestingEmpId).FirstOrDefault();
                }
            }
            List<EmpSalaryVM> empSalaryVM = _mapper.Map<List<EmpSalaryVM>>(empSalaries);
            AmountRequestVM model = new AmountRequestVM
            {
                Amounts = empSalaryVM
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                EmpSalary empSalary = await _amountService.GetEmpSalary(id);
                if (empSalary == null)
                {
                    return NotFound();
                }

                await _amountService.RemoveEmpSalary(empSalary.Id);
            }
            catch
            {

            }
            return RedirectToAction(nameof(Index));
        }

    }
}

EMS/Controllers/Leave/LeaveTypeController.cs
using AutoMapper;
using EMS.Data.Entities.Emp;
using EMS.Data.Entities.Leaves;
using EMS.Data.FormModels.EmpLeave;
using EMS.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EMS.Controllers.Leave
{
    [Authorize(Roles = "Admin,Superadmin")]
    public class LeaveTypeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;
        private readonly ILeaveTypeService _leaveTypeService;
        private readonly ILeaveAllocationService _leaveAllocationService;

        public LeaveTypeController(UserManager<Employee> userManager, IMapper mapper, ILeaveTypeService leaveTypeService,
                ILeaveAllocationService leaveAllocationService)
        {
            _userManager = userManager;
            _mapper = mapper;
            _leaveTypeService = leaveTypeService;
            _leaveAllocationService = leaveAllocationService;
        }

        public async Task<IActionResult> LeaveTypeList()
        {
            List<LeaveType> leavetypes = await _leaveTypeService.GetAllLeaveTypes();
            List<LeaveTypeVM> model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leavetypes.ToList());
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LeaveTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if(_leaveTypeService.GetAllLeaveTypes().Result.Any(x => x.Name == model.Name))
                {
                    ModelState.AddModelError("", "Leave Type already exist...");
                    return View(model);
                }    

                LeaveType leaveType = _mapper.Map<LeaveType>(model);
                leaveType.CreatedDate = DateTime.Now;
                leaveType.CreatedBy = _userManager.GetUserName(User);
                await _leaveTypeService.AddLeaveType(leaveType);
                await SetLeaveAllocation(leaveType.Id);
                return RedirectToAction("LeaveTypeList");
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(model);
            }
        }

        public async Task<ActionResult> SetLeaveAllocation(int id)
        {
            LeaveType leavetype = await _leaveTypeService.GetLeaveTypeById(id);
            var employees = await _userManager.GetUsersInRoleAsync("Employee");
            var period = DateTime.Now.Year;
            foreach (var emp in employees)
            {
                if (_leaveAllocationService.IsLeaveAllocationExists(emp.Id, id, period))
                    continue;

                LeaveAllocationVM allocation = new LeaveAllocationVM
                {
                    DateCreated = DateTime.Now,
                    EmployeeId = emp.Id,
                    LeaveTypeId = id,
                    NumberOfDays = leavetype.DefaultDays,
                    Period = DateTime.Now.Year
                };

                var leaveallocation = _mapper.Map<LeaveAllocation>(allocation);
                leaveallocation.CreatedDate = DateTime.Now;
                leaveallocation.CreatedBy = _userManager.GetUserName(User);
                await _leaveAllocationService.AddLeaveAllocation(leaveallocation);
            }

            return RedirectToAction("AllocateLeave");
        }

        public async Task<ActionResult> EditLeaveType(int id)
        {
            var leaveType = await _leaveTypeService.GetLeaveTypeById(id);
            if (leaveType is null)
            {
                return NotFound();
            }

            LeaveTypeVM leaveTypeVM = _mapper.Map<LeaveTypeVM>(leaveType);
            return View(leaveTypeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditLeaveType(LeaveTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                LeaveType leaveType = _mapper.Map<LeaveType>(model);
                await _leaveTypeService.UpdateLeaveType(leaveType);
                leaveType.UpdatedDate = DateTime.Now;
                leaveType.UpdatedBy = _userManager.GetUserName(User);

                return RedirectToAction("LeaveTypeList");
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteLeaveType(int id)
        {
            try
            {
                string empId = _userManager.GetUserId(User);
                if (!_leaveAllocationService.IsLeaveAllocationExists(empId, id, DateTime.Now.Year))
                {
                    LeaveType leavetype = await _leaveTypeService.GetLeaveTypeById(id);
                    if (leavetype == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        await _leaveTypeService.DeleteLeaveType(leavetype);
                    }
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("Something Went Wrong...", ex.Message);
            }

            return RedirectToAction("LeaveTypeList");
        }
    }
}

EMS/Controllers/MyprofileController.cs
using Data.FormModels;
using EMS.Data;
using EMS.Data.Entities.Emp;
using Ems1.Controllers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EMS.Controllers
{
    public class MyprofileController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private EmpDbContext _empDbContext;
        private readonly UserManager<Employee> _userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        public MyprofileController(ILogger<HomeController> logger, EmpDbContext empDbContext, UserManager<Employee> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
            _userManager = userManager;
            _empDbContext = empDbContext;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Edit()
        {
            var uid = _userManager.GetUserId(HttpContext.User);
            if (uid == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Employee user = _userManager.FindByIdAsync(uid).Result;
                if (user != null)
                {
                    EmployeeVM model = new EmployeeVM()
                    {
                        Firstname = user.Firstname,
                        Lastname = user.Lastname,
                        Address = user.Address,
                        DateofBirth = user.DateofBirth,
                        DateofJoin = user.DateofJoin,
                        AadharNumber = user.AadharNumber,

                    };

                    return View(model);
                }
            }
            return RedirectToAction("Index", "Home");

        }

        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeVM model)
        {
            var uid = _userManager.GetUserId(HttpContext.User);
            Employee user = _userManager.FindByIdAsync(uid).Result;
            if (user == null)
            {
                ViewBag.err = $"User with Id={model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                user.Firstname = model.Firstname;
                user.Lastname = model.Lastname;
                user.Address = model.Address;
                user.DateofBirth = model.DateofBirth;
                user.DateofJoin = model.DateofJoin;
                user.AadharNumber = model.AadharNumber;

                user.UpdatedBy = _userManager.GetUserName(User);
                user.UpdatedDate = DateTime.Now;

                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("MyProfileDetail");
                }
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }

            return View(model);

        }

        [HttpGet]
        public IActionResult MyProfileDetail()
        {
            var uid = _userManager.GetUserId(HttpContext.User);
            if (uid == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Employee user = _userManager.FindByIdAsync(uid).Result;
                if (user != null)
                {
                    EmployeeVM model = new EmployeeVM()
                    {
                        Firstname = user.Firstname,
                        Lastname = user.Lastname,
                        Address = user.Address,
                        DateofBirth = user.DateofBirth,
                        DateofJoin = user.DateofJoin,
                        AadharNumber = user.AadharNumber,
                    };
                    return View(model);
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

EMS/Views/Shared/_AdminLTE.cshtml
@using EMS.Data.Entities.Emp;
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@ViewData["Title"] - Employee Management System</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="~/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <span class="brand-text font-weight-light">Employee Management</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <hr />
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-home"></i>
                                <p>Home</p>
                            </a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a asp-action="EmployeList" asp-controller="Employe" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-users"></i>
                                    <p>Employee</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="LeaveTypeList" asp-controller="LeaveType" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-book-medical"></i>
                                    <p>Leave Types</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="LeaveAllocation" asp-action="ListEmployees" asp-area="">
                                    <i class="nav-icon far fa-address-book"></i>
                                    <p>Leave Allocation </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="LeaveRequest" asp-action="LeaveRequestList" asp-area="">
                                    <i class="nav-icon fas fa-pen-alt"></i>
                                    <p> Leave Request Log </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="MyProfileDetail" asp-controller="Myprofile" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-user-cog"></i>
                                    <p>My Profile</p>
                                </a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a asp-action="MyProfileDetail" asp-controller="Myprofile" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-user-cog"></i>
                                    <p>My Profile</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Amount" asp-action="EmpIndex" asp-area="">
                                    <i class="nav-icon fas fa-money-bill-wave"></i>
                                    <p>My Salary</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="MyLeave" asp-controller="LeaveRequest" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-list"></i>
                                    <p>My Leave</p>
                                </a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Superadmin"))
                        {
                            <li class="nav-item">
                                <a asp-action="EmployeList" asp-controller="Employe" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-users"></i>
                                    <p>Employee</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Amount" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-cash-register"></i>
                                    <p>Employee Salary</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="LeaveRequest" asp-action="LeaveRequestList" asp-area="">
                                    <i class="nav-icon fas fa-pen-alt"></i>
                                    <p>Employee LeaveRequest</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="LeaveTypeList" asp-controller="LeaveType" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-book-medical"></i>
                                    <p>Manage LeaveTypes</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-action="MyProfileDetail" asp-controller="Myprofile" asp-area="" class="nav-link">
                                    <i class="nav-icon fas fa-user-cog"></i>
                                    <p>My Profile</p>
                                </a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                @*   Styled by <a href="https://adminlte.io">AdminLTE.io</a>*@
            </div>
            <!-- Default to the left -->
            @*<strong>Copyright &copy; @DateTime.Now.Year Core Leave Management System.</strong> All rights reserved.*@
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

EMS/Views/Shared/_Layout.cshtml
@using EMS.Data.Entities.Emp;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EMS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @*<partial name="_LoginPartial" />*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @(DateTime.Now.Year) - EMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>