EMS/Controllers/Leave/LeaveRequestController.cs
using AutoMapper;
using EMS.Data.Entities.Emp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EMS.Data;
using EMS.Service.Interface;
using Microsoft.EntityFrameworkCore;
using EMS.Data.Entities.Leaves;
using Microsoft.AspNetCore.Mvc.Rendering;
using EMS.Service;
using EMS.Data.FormModels.EmpLeave;

namespace EMS.Controllers.Leave
{
    [Authorize]
    public class LeaveRequestController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IEmailSender _emailSender;
        private readonly ILeaveRequestService _leaveRequestService;
        private readonly ILeaveAllocationService _leaveAllocationService;
        private readonly ILeaveTypeService _leaveTypeService;
        private readonly UserManager<Employee> _userManager;
        public LeaveRequestController(IEmailSender emailSender, IMapper mapper, UserManager<Employee> userManager, 
            ILeaveRequestService leaveRequestService, ILeaveAllocationService leaveAllocationService, ILeaveTypeService leaveTypeService)
        {
            _emailSender = emailSender;
            _mapper = mapper;
            _userManager = userManager;
            _leaveRequestService = leaveRequestService;
            _leaveAllocationService = leaveAllocationService;
            _leaveTypeService = leaveTypeService;
        }

        [Authorize(Roles = "Admin,Superadmin")]
        public async Task<IActionResult> LeaveRequestList()
        {
            var leaveRequests = await _leaveRequestService.FindAll(
                includes: q => q.Include(x => x.RequestingEmployee).Include(x => x.LeaveType));

            List<LeaveRequestVM> leaveRequstsModel = _mapper.Map<List<LeaveRequestVM>>(leaveRequests);
            AdminLeaveRequestViewVM model = new AdminLeaveRequestViewVM
            {
                TotalRequests = leaveRequstsModel.Count,
                ApprovedRequests = leaveRequstsModel.Count(q => q.Approved == true),
                PendingRequests = leaveRequstsModel.Count(q => q.Approved == null),
                RejectedRequests = leaveRequstsModel.Count(q => q.Approved == false),
                LeaveRequests = leaveRequstsModel
            };

            return View(model);
        }

        [Authorize(Roles = "Employee")]
        public async Task<ActionResult> MyLeave()
        {
            Employee employee = await _userManager.GetUserAsync(User);
            var employeeid = employee.Id;
            var employeeAllocations = await _leaveAllocationService.FindAll(expression: q => q.EmployeeId == employeeid, includes: q => q.Include(x => x.LeaveType));

            var employeeRequests = await _leaveRequestService.FindAll(expression: q => q.RequestingEmpId == employeeid,
                includes: q => q.Include(x => x.RequestingEmployee).Include(x => x.LeaveType));

            var employeeAllocationsModel = _mapper.Map<List<LeaveAllocationVM>>(employeeAllocations);
            var employeeRequestsModel = _mapper.Map<List<LeaveRequestVM>>(employeeRequests);

            var model = new EmployeeLeaveRequestViewVM
            {
                LeaveAllocations = employeeAllocationsModel,
                LeaveRequests = employeeRequestsModel
            };

            return View(model);

        }

        [Authorize(Roles = "Employee")]
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var leaveTypes = await _leaveTypeService.GetAllLeaveTypes();
            var leaveTypeItems = leaveTypes.Select(q => new SelectListItem
            {
                Text = q.Name,
                Value = q.Id.ToString(),
            });

            CreateLeaveRequestVM model = new CreateLeaveRequestVM
            {
                LeaveTypes = leaveTypeItems
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLeaveRequestVM model)
        {
            try
            {
                DateTime startDate = new DateTime();
                DateTime endDate = new DateTime();

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if(model.StartDate.HasValue && model.EndDate.HasValue)
                {
                    startDate = model.StartDate.Value;
                    endDate = model.EndDate.Value;
                }

                List<LeaveType> leaveTypes = await _leaveTypeService.GetAllLeaveTypes();
                Employee employee = await _userManager.GetUserAsync(User);
                int period = DateTime.Now.Year;
                LeaveAllocation allocation = await _leaveAllocationService.Find(expression: q => q.EmployeeId == employee.Id
                                                    && q.Period == period
                                                    && q.LeaveTypeId == model.LeaveTypeId);
                int daysRequested = (endDate.Day - startDate.Day) + 1;
                var leaveTypeItems = leaveTypes.Select(q => new SelectListItem
                {
                    Text = q.Name,
                    Value = q.Id.ToString()
                });

                model.LeaveTypes = leaveTypeItems;
                if (allocation == null)
                {
                    ModelState.AddModelError("", "You Have No Days Left");
                }
                if (DateTime.Compare(startDate, endDate) > 1)
                {
                    ModelState.AddModelError("", "Start Date cannot be further in the future than the End Date");
                }
                if (daysRequested > allocation.NumberOfDays)
                {
                    ModelState.AddModelError("", "You Do Not Sufficient Days For This Request");
                }

                LeaveRequestVM leaveRequestModel = new LeaveRequestVM
                {
                    RequestingEmpId = employee.Id,
                    StartDate = startDate,
                    EndDate = endDate,
                    ApprovedById = null,
                    ApprovedBy = null,
                    DateRequested = DateTime.Now,
                    DateActioned = DateTime.Now,
                    LeaveTypeId = model.LeaveTypeId,
                    RequestComments = model.RequestComments
                };

                LeaveRequest leaveRequest = _mapper.Map<LeaveRequest>(leaveRequestModel);
                leaveRequest.CreatedDate = DateTime.Now;
                leaveRequest.CreatedBy = _userManager.GetUserName(User);
                await _leaveRequestService.AddLeaveRequest(leaveRequest);

                // Send Email to supervisor and requesting user
                await _emailSender.SendEmailAsync("admin@localhost.com", "New Leave Request",
                    $"Please review this leave request. <a href='UrlOfApp/{leaveRequest.Id}'>Click Here</a>");

                return RedirectToAction("MyLeave");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Something went wrong");
                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CancelRequest(int id)
        {
            LeaveRequest leaveRequest = await _leaveRequestService.GetLeaveRequestById(id);
            if (leaveRequest is not null)
            {
                await _leaveRequestService.RemoveLeaveRequest(leaveRequest);
            }

            return RedirectToAction("MyLeave");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateLeaveStatus(int id,bool status)
        {
            LeaveRequest leaveRequest = await _leaveRequestService.GetLeaveRequestById(id);
            if (leaveRequest is not null)
            {
                leaveRequest.Approved = status;
                await _leaveRequestService.UpdateLeaveRequest(leaveRequest);
            }

            return RedirectToAction("LeaveRequestList");
        }

        [HttpGet]
        public async Task<IActionResult> LeaveDetails(int id)
        {
            var leaveRequests = await _leaveRequestService.FindAll(
                includes: q => q.Include(x => x.RequestingEmployee).Include(x => x.LeaveType));

            if(leaveRequests is not null)
            {
                LeaveRequest leaveRequest = leaveRequests.Where(x => x.Id == id).FirstOrDefault();

                LeaveRequestVM leaveRequstsModel = _mapper.Map<LeaveRequestVM>(leaveRequest);
                return View(leaveRequstsModel);
            }

            return RedirectToAction("Index","Home");
        }
    }
}

EMS/Views/LeaveRequest/Create.cshtml
@model EMS.Data.FormModels.EmpLeave.CreateLeaveRequestVM
@{
    ViewData["Title"] = "Apply for leave";
}

<h1>Apply Leave</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-4 mb-2">
                <label asp-for="LeaveTypeId" class="control-label"></label>
                @Html.DropDownListFor(a => a.LeaveTypeId, new SelectList(Model.LeaveTypes, "Value", "Text"), "Select LeaveType", new { @class = "form-control" })
                <span asp-validation-for="LeaveTypeId" class="text-danger"></span>
            </div>
            <div class="row col-md-12 mb-2">
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control datepicker" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control datepicker" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-4 mb-2">
                <label asp-for="RequestComments" class="control-label"></label>
                <textarea asp-for="RequestComments" class="form-control"></textarea>
                <span asp-validation-for="RequestComments" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4 text-center align-items-center">
                <button type="submit" class="btn btn-primary">Request Leave</button>
                <button class="btn btn-secondary" asp-action="MyLeave">Back to List</button>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        $(function () {
            $(".datepicker").datepicker({
                dateFomat: "yy-mm-dd"
            });
        });
    </script>
}

EMS/Views/LeaveRequest/LeaveDetails.cshtml
@model EMS.Data.FormModels.EmpLeave.LeaveRequestVM
@{
    ViewData["Title"] = "Leave Detail";

}

<h1>Leave Detail</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestingEmployee.Firstname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestingEmployee.Firstname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveType.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateRequested)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateRequested)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestComments)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestComments)
        </dd>

    </dl>
</div>
<div>
    <div class="d-flex col-md-12 me-2">
        <form asp-action="UpdateLeaveStatus" asp-route-id="@Model.Id" asp-route-status="@true">
            <input type="submit" class="btn btn-outline-success m-1" value="Approve" />
        </form>
        <form asp-action="UpdateLeaveStatus" asp-route-id="@Model.Id" asp-route-status="@false">
            <input type="submit" class="btn btn-outline-danger m-1" value="Reject" />
        </form>
        <a asp-action="LeaveRequestList" class="m-1 btn btn-outline-secondary" asp-controller="LeaveRequest">Back to List</a>
    </div>

    @*<button type="submit" class="btn btn-outline-success badge badge-success m-2" asp-action="UpdateLeaveStatus" asp-route-id="@Model.Id" asp-route-status="@true">
    Approve </button> |
    <a class="btn btn-outline-danger badge badge-danger m-2" asp-action="UpdateLeaveStatus" asp-route-id="@Model.Id" asp-route-status="@false">
    Reject </a> |*@
</div>

EMS/Views/LeaveRequest/LeaveRequestList.cshtml
@using EMS.Constants;
@using EMS.Data.FormModels.EmpLeave;
@model AdminLeaveRequestViewVM

@{
    ViewData["Title"] = "Leave Requests";
}

<style>
    .disabled-link{
        pointer-events: none;
    }
</style>

<div class="row mb-2">
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-info"><i class="fas fa-tachometer-alt"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">@Model.TotalRequests</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.TotalRequests)</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-warning"><i class="fas fa-exclamation-circle"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">@Model.PendingRequests</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.PendingRequests)</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-success"><i class="far fa-check-circle"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">@Model.ApprovedRequests</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.ApprovedRequests)</span>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-danger"><i class="far fa-times-circle"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">@Model.RejectedRequests</span>
                <span class="info-box-number">@Html.DisplayNameFor(model => model.RejectedRequests)</span>
            </div>
        </div>
    </div>
</div>

<hr />
<h1>Leave Request Log</h1>
<hr />
<table id="tblData" class="table">
    <thead>
        <tr>
            <th> Employee Name </th>
            <th> Start Date </th>
            <th> End Date </th>
            <th> Leave Type </th>
            <th> Date Requested </th>
            <th> Approval Status </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequests)
        {
            <tr>
                <td>
                    @if(item.RequestingEmployee != null)
                        @Html.DisplayFor(modelItem => item.RequestingEmployee.Firstname) @Html.DisplayFor(modelItem => item.RequestingEmployee.Lastname)
                </td>
                <td> @Html.DisplayFor(modelItem => item.StartDate) </td>
                <td> @Html.DisplayFor(modelItem => item.EndDate) </td>
                <td> @(item.LeaveType != null ? Html.DisplayFor(modelItem => item.LeaveType.Name) : string.Empty) </td>
                <td> @Html.DisplayFor(modelItem => item.DateRequested) </td>
                <td>
                    @if (item.Cancelled)
                    {
                        <span class="badge badge-secondary">@(LeaveStatus.Cancelled)</span>
                    }
                    else if (item.Approved == true)
                    {
                        <span class="badge badge-success">@(LeaveStatus.Approved)</span>
                    }
                    else if (item.Approved == false)
                    {
                        <span class="badge badge-danger">@(LeaveStatus.Rejected)</span>
                    }
                    else
                    {
                        <span class="badge badge-warning">@(LeaveStatus.PendingApproval)l</span>
                    }
                </td>
                <td>
                    @if (!item.Cancelled)
                    {
                        <a class="btn btn-outline-primary @(item.Approved == true || item.Approved == false ? "disabled-link": "")" asp-action="LeaveDetails" asp-route-id="@item.Id">
                            <i class="fa fa-file"></i>Review
                        </a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

EMS/Views/LeaveRequest/MyLeave.cshtml
@using Data.FormModels;
@using EMS.Constants;
@using EMS.Data.FormModels.EmpLeave;
@model EmployeeLeaveRequestViewVM
@{
    ViewData["Title"] = "My Leave";
}

<p><a asp-area="" asp-controller="LeaveRequest" asp-action="Create" class="btn btn-primary">Apply For Leave</a></p>

@if (Model.LeaveAllocations is not null && Model.LeaveAllocations.Any())
{
    <h1>My Leave Allocations</h1>
    <div class="jumbotron">
        <div class="card">
            <ul class="list-group list-group-flush">
                @foreach (var item in Model.LeaveAllocations)
                {
                    if(item.LeaveType is not null)
                    {
                        <li class="list-group-item">
                            <h6>@item.LeaveType.Name <span class="badge badge-secondary">@item.NumberOfDays</span></h6>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
    <hr />
}

<h1>My Leave Records</h1>
<table id="tblData" class="table">
    <thead>
        <tr>
            <th>Leave Type</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Date Requested</th>
            <th>Approval State</th>
            <th>Cancel Request</th>
        </tr>
    </thead>
    <tbody>
        @if(Model is not null && Model.LeaveRequests is not null)
        {
            foreach (LeaveRequestVM item in Model.LeaveRequests)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.LeaveType.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.StartDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.EndDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.DateRequested, new { @value = item.DateRequested.ToString("yyyy-mm-dd") })</td>
                    <td>
                        @if (item.Cancelled)
                        {
                            <span class="badge badge-secondary">Cancelled</span>
                        }
                        else if (item.Approved == true)
                        {
                            <span class="badge badge-success">@LeaveStatus.Approved</span>
                        }
                        else if (item.Approved == false)
                        {
                            <span class="badge badge-danger">@LeaveStatus.Rejected</span>
                        }
                        else
                        {
                            <span class="badge badge-warning">@LeaveStatus.PendingApproval</span>
                        }
                    </td>
                    <td>
                        @if ((!item.Cancelled && item.StartDate > DateTime.Now))
                        {
                            <div class="row">
                                <div class="col-2">
                                    <form asp-action="CancelRequest" asp-route-id="@item.Id" method="post">
                                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to cancel this request?')">
                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>