EMS/Controllers/Leave/LeaveAllocationController.cs
using AutoMapper;
using Data.FormModels;
using EMS.Data.Entities.Emp;
using EMS.Data.Entities.Leaves;
using EMS.Data.FormModels.EmpLeave;
using EMS.Service.Interface;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EMS.Controllers.Leave
{
    public class LeaveAllocationController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILeaveTypeService _leaveTypeService;
        private readonly ILeaveAllocationService _leaveAllocationService;
        private readonly UserManager<Employee> _userManager;

        public LeaveAllocationController(IMapper mapper, UserManager<Employee> userManager, ILeaveTypeService leaveTypeService
                , ILeaveAllocationService leaveAllocationService)
        {
            _mapper = mapper;
            _userManager = userManager;
            _leaveTypeService = leaveTypeService;
            _leaveAllocationService = leaveAllocationService;
        }

        public async Task<ActionResult> ListEmployees()
        {
            var employees = await _userManager.GetUsersInRoleAsync("Employee");
            var model = _mapper.Map<List<EmployeeVM>>(employees);
            return View(model);
        }

        public async Task<ActionResult> LeaveAllocationDetail(string id)
        {
            var employee = _mapper.Map<EmployeeVM>(await _userManager.FindByIdAsync(id));
            int period = DateTime.Now.Year;
            var records = await _leaveAllocationService.FindAll(
                expression: q => q.EmployeeId == id && q.Period == period, includes: q => q.Include(x => x.LeaveType));

            List<LeaveAllocationVM> allocations = _mapper.Map<List<LeaveAllocationVM>>(records);

            ViewAllocationsVM model = new ViewAllocationsVM
            {
                Employee = employee,
                LeaveAllocations = allocations
            };

            return View(model);
        }

        public async Task<ActionResult> EditLeaveAllocation(int id)
        {
            LeaveAllocation leaveAllocation = await _leaveAllocationService.Find(q => q.Id == id,
                includes: q => q.Include(x => x.Employee).Include(x => x.LeaveType));
            EditLeaveAllocationVM model = _mapper.Map<EditLeaveAllocationVM>(leaveAllocation);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditLeaveAllocation(EditLeaveAllocationVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                LeaveAllocation record = await _leaveAllocationService.GetById(model.Id);
                record.NumberOfDays = model.NumberOfDays;
                record.UpdatedDate = DateTime.Now;
                record.UpdatedBy = _userManager.GetUserName(User);
                await _leaveAllocationService.UpdateLeaveAllocation(record);

                return RedirectToAction(nameof(LeaveAllocationDetail), new { id = model.EmployeeId });
            }
            catch
            {
                return View(model);
            }
        }
    }
}

EMS/Views/LeaveAllocation/EditLeaveAllocation.cshtml
@model EMS.Data.FormModels.EmpLeave.EditLeaveAllocationVM
@{
    ViewData["Title"] = "Edit Leave Allocation";
}

<h1>Editing @Model.LeaveType.Name Allocation for @Model.Employee.Lastname, @Model.Employee.Firstname </h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditLeaveAllocation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="EmployeeId" />
            <input type="hidden" asp-for="Employee" />
            <input type="hidden" asp-for="LeaveType" />
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-outline-secondary" asp-action="LeaveAllocationDetail" asp-route-id="@Model.EmployeeId">Back to Details</a>
            </div>
        </form>
    </div>
</div>

EMS/Views/LeaveAllocation/LeaveAllocationDetail.cshtml
@model EMS.Data.FormModels.EmpLeave.ViewAllocationsVM
@{
    ViewData["Title"] = "Leave Allocation Detail";
}

@if (Model is not null && Model.Employee is not null)
{
    <h1>Leave Allocation Details For - @Model.Employee.Lastname, @Model.Employee.Firstname</h1>
    <div class="m-2">
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Employee.Firstname)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Employee.Firstname)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Employee.Lastname)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Employee.Lastname)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Employee.DateofBirth)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Employee.DateofBirth)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Employee.DateofJoin)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Employee.DateofJoin)
            </dd>
        </dl>
    </div>
    <hr />
}

<h2>Leave Allocations</h2>
@if (Model is not null && Model.LeaveAllocations.Any())
{
    <div class="card">
        <ul class="list-group list-group-flush">
            @foreach (var item in Model.LeaveAllocations)
            {
                <li class="list-group-item">
                    <h6>
                        @item.LeaveType.Name
                        <span class="badge badge-secondary">@item.NumberOfDays</span>
                        <a asp-action="EditLeaveAllocation" asp-route-id="@item.Id" class="btn btn-warning">
                            <i class="fa fa-pencil"></i> Edit
                        </a>
                        <a class="btn btn-outline-secondary" asp-action="ListEmployees" asp-controller="LeaveAllocation">Back to List</a>
                    </h6>
                </li>
            }
        </ul>
    </div>
}
else
{
    <div class="card">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                No Leave Type Allocated..!
            </li>
        </ul>
    </div>
}

EMS/Views/LeaveAllocation/ListEmployees.cshtml
@model IEnumerable<Data.FormModels.EmployeeVM>
@{
    ViewData["Title"] = "List Employees";
}

<h1>List Of Employees</h1>

<table id="tblData" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Firstname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lastname)
                </td>

                <td>
                    <a class="btn btn-outline-success" asp-action="LeaveAllocationDetail" asp-route-id="@item.Id">
                        <i class="fa fa-search"></i> Leave Allocation Detail
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>